import Link from "next/link";
const services=[["MRO – Global Sourcing","mro-global-sourcing","Source critical MRO requirements through a structured supplier network."],["CAPEX – Comprehensive Industrial Material Supply","capex-material-supply","Project-focused material sourcing with technical and commercial coordination."],["Procurement Consulting – CAPEX & OPEX","procurement-consulting","Improve procurement strategy, supplier decisions and commercial control."],["Installation, Commissioning, Maintenance & Repair","installation-commissioning-maintenance-repair","Coordinate installation, commissioning, maintenance and repair requirements."],["Procurement Audit","procurement-audit","Review procurement controls, compliance, documentation and process gaps."],["Internal Audit","internal-audit","Strengthen operational controls, governance and risk visibility."],["Digital Marketing","digital-marketing","Build a credible B2B digital presence for industrial businesses."],["Graphic Design","graphic-design","Professional brand, presentation and visual communication for B2B businesses."]];
const products=[["MRO Products","mro-products"],["Instrumentation & Automation","instrumentation-automation"],["Packaging Solutions","packaging-solutions"],["Industrial Machinery","industrial-machinery"],["Corporate Gifts","corporate-gifts"],["Infrastructure Solutions","infrastructure-solutions"]];
const industries=[["Automotive","automotive"],["FMCG","fmcg"],["Food & Beverage","food-beverage"],["Alcoholic Beverages","alcoholic-beverages"],["Hospitality","hospitality"],["Manufacturing","manufacturing"],["Pharmaceutical","pharmaceutical"],["Power & Energy","power-energy"],["Retail","retail"],["Oil & Gas","oil-gas"],["Defence","defence"],["Health & Safety","health-safety"]];
export default function Home(){return <main>
<section className="heroHome"><img src="/images/hero.jpg" alt="Industrial procurement and supply"/><div className="heroShade"/><div className="container heroContent"><span className="eyebrow">MRO • CAPEX • OPEX • INDUSTRIAL SUPPLY</span><h1>Industrial sourcing.<br/><em>Reliable supply.</em><br/>Stronger operations.</h1><p>RKV Industrial Solutions helps businesses source, procure and support critical industrial requirements with clear coordination and dependable execution.</p><div className="heroBtns"><Link className="btn btn-orange" href="/contact">Request a Quote ↗</Link><Link className="btn btn-outlineLight" href="/services">Explore Services</Link></div><div className="heroProof"><span><b>01</b> Requirement clarity</span><span><b>02</b> Supplier coordination</span><span><b>03</b> Delivery follow-up</span></div></div></section>
<section className="sectorBar"><div className="container sectorIn"><span>Supporting businesses across</span><b>INDUSTRIAL</b><b>MANUFACTURING</b><b>FMCG</b><b>ENERGY</b><b>PHARMA</b></div></section>
<section className="section"><div className="container aboutHome"><div><span className="eyebrow dark">ABOUT RKV</span><h2>A procurement partner built around accountability.</h2><p>RKV Industrial Solutions brings together sourcing, industrial material supply, procurement consulting, audits and operational support under one business relationship.</p><p>Our approach is simple: understand the requirement, coordinate the right sources, keep communication clear and follow the requirement through.</p><div className="aboutMetrics"><div><b>01</b><span>Requirement-first approach</span></div><div><b>02</b><span>Commercial discipline</span></div><div><b>03</b><span>Execution support</span></div></div><Link className="textLink" href="/about">More about RKV →</Link></div><div className="imageFrame"><img src="/images/about.jpg" alt="RKV procurement team"/></div></div></section>
<section className="section soft"><div className="container"><div className="sectionHead"><div><span className="eyebrow dark">OUR SERVICES</span><h2>Eight capabilities. One accountable partner.</h2></div><Link className="textLink" href="/services">View all →</Link></div><div className="serviceHomeGrid">{services.map(([t,s,d],i)=><Link className="serviceHomeCard" href={`/services/${s}`} key={s}><div className="serviceImg"><img src={`/images/services/${s}.jpg`} alt={t}/><span>0{i+1}</span></div><div><span className="eyebrow dark">RKV SERVICE</span><h3>{t}</h3><p>{d}</p><b>Explore capability →</b></div></Link>)}</div></div></section>
<section className="section"><div className="container processHome"><div className="processIntro"><span className="eyebrow dark">HOW WE WORK</span><h2>A clear route from requirement to delivery.</h2><p>Industrial procurement becomes easier when every handover is visible and every stakeholder knows the next step.</p><Link className="btn btn-navy" href="/contact">Start a Requirement</Link></div><div className="processTimeline"><div><span>01</span><h3>Understand</h3><p>Specification, application, quantity and urgency.</p></div><div><span>02</span><h3>Source</h3><p>Identify suitable suppliers and options.</p></div><div><span>03</span><h3>Compare</h3><p>Technical and commercial evaluation.</p></div><div><span>04</span><h3>Coordinate</h3><p>Orders, documents, dispatch and follow-up.</p></div></div></div></section>
<section className="section productHome"><div className="container"><div className="sectionHead"><div><span className="eyebrow dark">PRODUCT SOLUTIONS</span><h2>Source around the specification.</h2></div><Link className="textLink" href="/products">View products →</Link></div><div className="productHomeGrid">{products.map(([t,s],i)=><Link href={`/products/${s}`} key={s}><img src={`/images/products/${s}.jpg`} alt={t}/><div><span>0{i+1}</span><h3>{t}</h3><b>Explore →</b></div></Link>)}</div></div></section>
<section className="section soft"><div className="container"><div className="sectionHead"><div><span className="eyebrow dark">INDUSTRIES</span><h2>Built for sectors where continuity matters.</h2></div><Link className="textLink" href="/industries">All industries →</Link></div><div className="industryHomeGrid">{industries.map(([t,s],i)=><Link href={`/industries/${s}`} key={s}><span>{String(i+1).padStart(2,"0")}</span><b>{t}</b><em>↗</em></Link>)}</div></div></section>
<section className="section whyHome"><div className="container twoCol"><div><span className="eyebrow dark">WHY RKV</span><h2>Dependable sourcing is about more than price.</h2><p>Industrial procurement affects uptime, project milestones, quality, cash flow and operational confidence. Our work is designed around those realities.</p></div><div className="whyCards"><div><b>Requirement clarity</b><span>Reduce avoidable back-and-forth before sourcing begins.</span></div><div><b>Supplier coordination</b><span>Keep commercial and technical communication organized.</span></div><div><b>Execution visibility</b><span>Follow the requirement through delivery and closure.</span></div></div></div></section>
<section className="ctaBand"><div className="container ctaInner"><div><span className="eyebrow">READY TO SOURCE BETTER?</span><h2>Tell us what your operation needs.</h2><p>Share a part number, drawing, specification, quantity or project scope.</p></div><Link className="btn btn-orange" href="/contact">Talk to RKV ↗</Link></div></section>
<a className="floatingWhatsApp" href="https://wa.me/918789856983" target="_blank" rel="noopener noreferrer" aria-label="Chat on WhatsApp"><span>◔</span><b>WhatsApp</b></a>
</main>}